version: '3'

services:
  app:
    image: 'bz/tax_rates:latest'
    container_name: app
    ports:
      - "9000:8080"
    depends_on:
      - test_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080

  test_db:
    image: 'postgres:13.1-alpine'
    container_name: test_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres